=== turker/Dissertation/Tests/EventSizeTests/SimConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="test">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="test_case">
          <xs:complexType>
            <xs:attribute name="comment" type="xs:string" use="required" />
            <xs:attribute name="db" type="xs:string" use="required" />
            <xs:attribute name="id" type="xs:positiveInteger" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="input_generator" maxOccurs="1" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="parameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="value" type="xs:double" />
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="type" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="deployment">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="cpu" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="xdaqexecutive" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="application">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element maxOccurs="unbounded" name="appparam">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="value" type="xs:double" />
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required" />
                                    <xs:attribute name="type" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:positiveInteger" use="required" />
                              <xs:attribute name="monperf" type="xs:boolean" use="required" />
                              <xs:attribute name="name" type="xs:string" use="required" />
                              <xs:attribute name="nbOfInstances" type="xs:positiveInteger" use="required" />
                              <xs:attribute name="unique_id" type="xs:positiveInteger" use="required" />
                              <xs:attribute name="minExecTime" type="xs:positiveInteger" use="required" />
                              <xs:attribute name="maxExecTime" type="xs:positiveInteger" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="port" type="xs:unsignedShort" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="ip" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="dataflow">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="connection">
                <xs:complexType>
                  <xs:attribute name="dstApp" type="xs:positiveInteger" use="required" />
                  <xs:attribute name="srcApp" type="xs:positiveInteger" use="required" />
                  <xs:attribute name="dstInstance" type="xs:positiveInteger" use="required" />
                  <xs:attribute name="srcInstance" type="xs:positiveInteger" use="required" />                  
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="performance">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="probe">
                <xs:complexType>
                  <xs:attribute name="metric" type="xs:string" use="required" />
                  <xs:attribute name="negative" type="xs:string" use="required" />
                  <xs:attribute name="positive" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== turker/Dissertation/Tests/EventSizeTests/4by4/SimConfig_EventSizeSweep_4x4_20.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SimConfig.xsd">

  <test_case comment="Size Sweep 4x4" db="XDAQSim.sqlite" id="10"/>

  <input_generator>
    <parameter name="NumberOfDataSources" type="Lognormal">
      <value>8</value>
    </parameter>
    <parameter name="EventSizeMean" type="Lognormal">
      <value>838860</value>
    </parameter>
    <parameter name="EventSizeSigma" type="Lognormal">
      <value>13000</value>
    </parameter>
    <parameter name="BlockSize" type="Lognormal">
      <value>4096</value>
    </parameter>
  </input_generator>

  <deployment>
    <cpu ip="192.168.1.1">
      <xdaqexecutive port="4000">
        <application id="10" maxExecTime="10" minExecTime="3" monperf="true" name="RU" nbOfInstances="4" unique_id="1">
          <appparam name="blockFIFOCapacity" type="double">
            <value>4096</value>
          </appparam>
        </application>
        <application id="11" maxExecTime="15" minExecTime="3" monperf="true" name="BU" nbOfInstances="4" unique_id="4">
          <appparam name="RU_SEND_PACKING" type="double">
            <value>8</value>
          </appparam>
          <appparam name="EVM_ALLOCATE_CLEAR_PACKING" type="double">
            <value>8</value>
          </appparam>
        </application>
        <application id="12" maxExecTime="10" minExecTime="3" monperf="true" name="EVM" nbOfInstances="1" unique_id="2">
          <appparam name="MAX_BUS" type="double">
            <value>8</value>
          </appparam>
          <appparam name="nbEvtIdsInBuilder" type="double">
            <value>32</value>
          </appparam>
          <appparam name="MAX_RUS" type="double">
            <value>8</value>
          </appparam>
          <appparam name="maxEvtsUnderConstruction" type="double">
            <value>32</value>
          </appparam>
          <appparam name="RU_READOUT_PACKING" type="double">
            <value>8</value>
          </appparam>
          <appparam name="DEFAULT_NB_EVENTS" type="double">
            <value>64</value>
          </appparam>
          <appparam name="MAX_BU_RESOURCES" type="double">
            <value>8</value>
          </appparam>
        </application>
        <application id="13" maxExecTime="5" minExecTime="1" monperf="false" name="PT" nbOfInstances="1" unique_id="3"/>
      </xdaqexecutive>
    </cpu>
  </deployment>

  <dataflow>
    <connection dstApp="2" dstInstance="1" srcApp="1" srcInstance="1"/>
    <connection dstApp="1" dstInstance="1" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="1" srcInstance="2"/>
    <connection dstApp="1" dstInstance="2" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="1" srcInstance="3"/>
    <connection dstApp="1" dstInstance="3" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="1" srcInstance="4"/>
    <connection dstApp="1" dstInstance="4" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="4" srcInstance="1"/>
    <connection dstApp="4" dstInstance="1" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="4" srcInstance="2"/>
    <connection dstApp="4" dstInstance="2" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="4" srcInstance="3"/>
    <connection dstApp="4" dstInstance="3" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="4" srcInstance="4"/>
    <connection dstApp="4" dstInstance="4" srcApp="2" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="4" srcInstance="1"/>
    <connection dstApp="4" dstInstance="1" srcApp="3" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="4" srcInstance="2"/>
    <connection dstApp="4" dstInstance="2" srcApp="3" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="4" srcInstance="3"/>
    <connection dstApp="4" dstInstance="3" srcApp="3" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="4" srcInstance="4"/>
    <connection dstApp="4" dstInstance="4" srcApp="3" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="2" srcInstance="1"/>
    <connection dstApp="2" dstInstance="1" srcApp="3" srcInstance="1"/>
    <connection dstApp="4" dstInstance="1" srcApp="1" srcInstance="1"/>
    <connection dstApp="1" dstInstance="1" srcApp="4" srcInstance="1"/>
    <connection dstApp="4" dstInstance="2" srcApp="1" srcInstance="1"/>
    <connection dstApp="1" dstInstance="1" srcApp="4" srcInstance="2"/>
    <connection dstApp="4" dstInstance="3" srcApp="1" srcInstance="1"/>
    <connection dstApp="1" dstInstance="1" srcApp="4" srcInstance="3"/>
    <connection dstApp="4" dstInstance="4" srcApp="1" srcInstance="1"/>
    <connection dstApp="1" dstInstance="1" srcApp="4" srcInstance="4"/>
    <connection dstApp="4" dstInstance="1" srcApp="1" srcInstance="2"/>
    <connection dstApp="1" dstInstance="2" srcApp="4" srcInstance="1"/>
    <connection dstApp="4" dstInstance="2" srcApp="1" srcInstance="2"/>
    <connection dstApp="1" dstInstance="2" srcApp="4" srcInstance="2"/>
    <connection dstApp="4" dstInstance="3" srcApp="1" srcInstance="2"/>
    <connection dstApp="1" dstInstance="2" srcApp="4" srcInstance="3"/>
    <connection dstApp="4" dstInstance="4" srcApp="1" srcInstance="2"/>
    <connection dstApp="1" dstInstance="2" srcApp="4" srcInstance="4"/>
    <connection dstApp="4" dstInstance="1" srcApp="1" srcInstance="3"/>
    <connection dstApp="1" dstInstance="3" srcApp="4" srcInstance="1"/>
    <connection dstApp="4" dstInstance="2" srcApp="1" srcInstance="3"/>
    <connection dstApp="1" dstInstance="3" srcApp="4" srcInstance="2"/>
    <connection dstApp="4" dstInstance="3" srcApp="1" srcInstance="3"/>
    <connection dstApp="1" dstInstance="3" srcApp="4" srcInstance="3"/>
    <connection dstApp="4" dstInstance="4" srcApp="1" srcInstance="3"/>
    <connection dstApp="1" dstInstance="3" srcApp="4" srcInstance="4"/>
    <connection dstApp="4" dstInstance="1" srcApp="1" srcInstance="4"/>
    <connection dstApp="1" dstInstance="4" srcApp="4" srcInstance="1"/>
    <connection dstApp="4" dstInstance="2" srcApp="1" srcInstance="4"/>
    <connection dstApp="1" dstInstance="4" srcApp="4" srcInstance="2"/>
    <connection dstApp="4" dstInstance="3" srcApp="1" srcInstance="4"/>
    <connection dstApp="1" dstInstance="4" srcApp="4" srcInstance="3"/>
    <connection dstApp="4" dstInstance="4" srcApp="1" srcInstance="4"/>
    <connection dstApp="1" dstInstance="4" srcApp="4" srcInstance="4"/>
    <connection dstApp="3" dstInstance="1" srcApp="1" srcInstance="1"/>
    <connection dstApp="1" dstInstance="1" srcApp="3" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="1" srcInstance="2"/>
    <connection dstApp="1" dstInstance="2" srcApp="3" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="1" srcInstance="3"/>
    <connection dstApp="1" dstInstance="3" srcApp="3" srcInstance="1"/>
    <connection dstApp="3" dstInstance="1" srcApp="1" srcInstance="4"/>
    <connection dstApp="1" dstInstance="4" srcApp="3" srcInstance="1"/>
  </dataflow>

  <performance>
    <probe metric="Throughput" negative="RU_in" positive="EVM_out"/>
    <probe metric="Throughput" negative="RU_in" positive="RU_out"/>
    <probe metric="Throughput" negative="BU_in" positive="BU_out"/>
    <probe metric="Average Event Size" negative="EVM_in" positive="BU_out"/>
    <probe metric="Latency" negative="EVM_in" positive="BU_out"/>
  </performance>

</test>
